### ISSUE TITLE
 lite-monitoring-web 项目本地启动报错

### ISSUE THREAD

**Issue by voidba** [waylau/lite-monitoring#1]
你好，大佬，在实践书中 lite-monitoring 代码时候。
 lite-monitoring-web 项目本地启动报错如下：
![image](https://user-images.githubusercontent.com/67100564/167242538-c107d922-7453-4a44-ba4c-53f30930d64e.png)
本地Resources 已经配置了lite-spring.xml ，但是读取不到。
运行 new LiteJettyServer().run(args); 启动就报上面图片的错误，运行环境的IDEA ，JDK 1.8

**Comment by waylau** [comment]
@JingGo2020  看报错信息，是说你没有配置数据源？
